# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e4c0c3aed8d54773a9e7bc244af9ba86f7fdf6f518f001de83772dd727efb7878d400cb4dc442468432cab7e328bb304bd285a6963cf0949b8de2115c92a1a

test:
  secret_key_base: 8ca8ca2e3d3e77de55f7902174914d20a17f962491e607e5272f9190dc9acd36940cb4ab4d2f59dd388bc700be3bee77e98ec75bf5242d85c7fc7be269ab219f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
